### ISSUE TITLE
DockerHub Availability

### ISSUE THREAD

**Issue by matant94** [mwmason/standardnotes-onecontainer#1]
May you publish it on Docker Hub to make more easy the deploy on Synology NAS?

**Comment by mwmason** [comment]
Hi,
There's actually a new release of s6-overlay which I haven't had a chance to update to.  I will need to do that before I can publish to Docker Hub.  It's on my todo list.

**Comment by matant94** [comment]
Thanks so much I really loved your work

**Comment by mwmason** [comment]
> May you publish it on Docker Hub to make more easy the deploy on Synology NAS?

hi @matant94 - I've been able to upgrade to s6-overlay v3.  Mostly painless.  And I've also been able to deploy the most recent version of sn (auth,apigw and syncing-server).

I've been using Dockerfile - locally I use Portainer and my prod is GC.  So I'm not familiar with what's required to publish to Docker Hub - can you provide some guidance on what would be needed?

**Comment by matant94** [comment]
Sorry for really slow answer, I use 3 Synology DS (720+, 918+, 920+) and I pretend to use Standardnotes using docker on DSM 7

**Comment by mwmason** [comment]
hi @matant94, published this release to Docker hub [here](https://hub.docker.com/repository/docker/mwmason/standardnotes-onecontainer).

**Comment by matant94** [comment]
Thank you soon i try to deploy it on my NASs
